/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.test.junit5;

import java.nio.file.Paths;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

/**
 * Verifies that a JUnit5 test class doesn't generate any file or directory outside the module's {@code target}
 * directory. The forked test JVM runs with the module's base directory as its working directory; any file created
 * there (typically through a relative path such as {@code new File("foo")}) leaks outside the {@code target} directory
 * and is thus not removed by {@code mvn clean}, polluting the source tree and causing errors on the CI.
 * <p>
 * Note that temporary files created through {@link java.io.File#createTempFile} or JUnit's {@code @TempDir} don't leak
 * since we force {@code java.io.tmpdir} to point inside {@code target} in the Maven Surefire/Failsafe configuration.
 *
 * @version $Id$
 * @since 18.5.0RC1
 */
public class CaptureWorkingDirectoryFilesExtension implements BeforeAllCallback, AfterAllCallback
{
    private static final String CAPTUREWORKINGDIRSKIP_PROPERTY = "xwiki.surefire.captureworkingdir.skip";

    private static final ExtensionContext.Namespace NAMESPACE =
        ExtensionContext.Namespace.create(CaptureWorkingDirectoryFilesExtension.class);

    private static final String SNAPSHOT = "snapshot";

    // Directories that legitimately live in a module and that are removed by "mvn clean". We don't report files
    // generated inside them since that's exactly where test-generated files should go.
    private static final Set<String> EXCLUDED = Set.of("target", "target-eclipse");

    private static Boolean skip;

    @Override
    public void beforeAll(ExtensionContext extensionContext)
    {
        if (!shouldSkip()) {
            getStore(extensionContext).put(SNAPSHOT, listWorkingDirectoryEntries());
        }
    }

    @Override
    public void afterAll(ExtensionContext extensionContext)
    {
        if (shouldSkip()) {
            return;
        }

        Set<String> snapshot = getStore(extensionContext).get(SNAPSHOT, Set.class);
        if (snapshot == null) {
            return;
        }

        Set<String> leaked = new TreeSet<>(listWorkingDirectoryEntries());
        leaked.removeAll(snapshot);
        if (!leaked.isEmpty()) {
            throw new AssertionError(String.format("The test class [%s] generated the following file(s)/directory(ies) "
                + "outside of the \"target\" directory: %s (in [%s]). All files generated by tests must be located "
                + "under the module's \"target\" directory so that they're removed by \"mvn clean\" and don't leak "
                + "outside of the build workspace. Use JUnit's @TempDir, @XWikiTempDir or XWikiTempDirUtil to create "
                + "temporary files/directories.", extensionContext.getRequiredTestClass().getName(), leaked,
                Paths.get("").toAbsolutePath()));
        }
    }

    /**
     * @return the names of the immediate children of the working directory (the module's base directory), excluding
     *         the build output directories. Listing only the immediate children is enough: a relative path always
     *         creates at least one new immediate child (e.g. {@code new File("a/b")} creates the {@code a} directory).
     */
    private Set<String> listWorkingDirectoryEntries()
    {
        String[] names = Paths.get("").toAbsolutePath().toFile().list();
        Set<String> result = new HashSet<>();
        if (names != null) {
            for (String name : names) {
                if (!EXCLUDED.contains(name)) {
                    result.add(name);
                }
            }
        }
        return result;
    }

    private static ExtensionContext.Store getStore(ExtensionContext context)
    {
        return context.getStore(NAMESPACE);
    }

    /**
     * @return true if the check should be skipped or false otherwise. The defined System property is checked first and
     *         if it doesn't exist, the Maven property of the same name is read from the current {@code pom.xml}
     */
    static boolean shouldSkip()
    {
        if (skip == null) {
            String value = SurefirePropertyUtils.getPropertyValue(CAPTUREWORKINGDIRSKIP_PROPERTY);
            skip = Boolean.parseBoolean(value);
        }
        return skip;
    }
}
