/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.tool.checkstyle;

import com.puppycrawl.tools.checkstyle.api.AbstractCheck;
import com.puppycrawl.tools.checkstyle.api.DetailAST;
import com.puppycrawl.tools.checkstyle.api.FullIdent;
import com.puppycrawl.tools.checkstyle.api.TokenTypes;

/**
 * Verify that tests don't generate files outside the module's {@code target} directory, by forbidding the patterns
 * that lead to it:
 * <ul>
 *   <li>hardcoding the system temporary directory ({@code /tmp} or {@code /var/tmp}),</li>
 *   <li>calling {@code File.createTempFile(prefix, suffix)} without an explicit parent directory (it defaults to the
 *       system temporary directory),</li>
 *   <li>calling {@code Files.createTempFile}/{@code Files.createTempDirectory} without a parent directory (i.e., with a
 *       String literal as first argument).</li>
 * </ul>
 * This check is meant to be applied to test sources only (the standard way to generate temporary files in a test is to
 * use JUnit's {@code @TempDir}, which is located under {@code target}).
 *
 * @version $Id$
 * @since 18.5.0RC1
 */
public class TemporaryFileCheck extends AbstractCheck
{
    private static final String CREATE_TEMP_FILE = "createTempFile";

    private static final String CREATE_TEMP_DIRECTORY = "createTempDirectory";

    // Note: messages are processed by java.text.MessageFormat (single quotes are special), so they must not contain
    // any apostrophe.
    private static final String ADVICE =
        " Use JUnit @TempDir or a path located under the module \"target\" directory so that files generated by the "
        + "test do not leak outside of it.";

    @Override
    public int[] getDefaultTokens()
    {
        return new int[] {TokenTypes.STRING_LITERAL, TokenTypes.METHOD_CALL};
    }

    @Override
    public int[] getAcceptableTokens()
    {
        return getDefaultTokens();
    }

    @Override
    public int[] getRequiredTokens()
    {
        return getDefaultTokens();
    }

    @Override
    public void visitToken(DetailAST ast)
    {
        switch (ast.getType()) {
            case TokenTypes.STRING_LITERAL:
                checkStringLiteral(ast);
                break;
            case TokenTypes.METHOD_CALL:
                checkMethodCall(ast);
                break;
            default:
                break;
        }
    }

    private void checkStringLiteral(DetailAST ast)
    {
        // The token text includes the surrounding double quotes, e.g. the 3 characters "/a get reported as ["/a].
        String text = ast.getText();
        String value = text.substring(1, text.length() - 1);
        if (isSystemTemporaryDirectory(value)) {
            log(ast, "Do not hardcode the system temporary directory in a test." + ADVICE);
        }
    }

    /**
     * @param value a String literal value
     * @return true if the value is the system temporary directory ({@code /tmp} or {@code /var/tmp}) or a path located
     *         under it. We match on a path-segment boundary so that unrelated directories that merely *start* with the
     *         characters {@code /tmp} (e.g. {@code /tmpdir}) are not reported.
     */
    private boolean isSystemTemporaryDirectory(String value)
    {
        return isDirectoryOrUnder(value, "/tmp") || isDirectoryOrUnder(value, "/var/tmp");
    }

    private boolean isDirectoryOrUnder(String value, String directory)
    {
        return value.equals(directory) || value.startsWith(directory + "/");
    }

    private void checkMethodCall(DetailAST ast)
    {
        DetailAST dot = ast.getFirstChild();
        if (dot.getType() != TokenTypes.DOT) {
            return;
        }
        String fullName = FullIdent.createFullIdent(dot).getText();
        DetailAST arguments = ast.findFirstToken(TokenTypes.ELIST);
        if (("File." + CREATE_TEMP_FILE).equals(fullName) && arguments.getChildCount(TokenTypes.EXPR) == 2) {
            log(ast, "Do not call File.createTempFile() without an explicit parent directory in a test." + ADVICE);
        } else if (("Files." + CREATE_TEMP_FILE).equals(fullName) && firstArgumentIsStringLiteral(arguments)) {
            log(ast, "Do not call Files.createTempFile() without a parent directory in a test." + ADVICE);
        } else if (("Files." + CREATE_TEMP_DIRECTORY).equals(fullName) && firstArgumentIsStringLiteral(arguments)) {
            log(ast, "Do not call Files.createTempDirectory() without a parent directory in a test." + ADVICE);
        }
    }

    private boolean firstArgumentIsStringLiteral(DetailAST arguments)
    {
        DetailAST firstExpression = arguments.findFirstToken(TokenTypes.EXPR);
        return firstExpression != null && firstExpression.getFirstChild() != null
            && firstExpression.getFirstChild().getType() == TokenTypes.STRING_LITERAL;
    }
}
