/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.tool.checkstyle;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport;
import com.puppycrawl.tools.checkstyle.DefaultConfiguration;

/**
 * Unit tests for {@link TemporaryFileCheck}.
 *
 * @version $Id$
 * @since 18.5.0RC1
 */
class TemporaryFileCheckTest extends AbstractModuleTestSupport
{
    private static final String ADVICE =
        " Use JUnit @TempDir or a path located under the module \"target\" directory so that files generated by the "
        + "test do not leak outside of it.";

    private DefaultConfiguration checkConfig;

    @BeforeEach
    void setUp()
    {
        this.checkConfig = createModuleConfig(TemporaryFileCheck.class);
    }

    @Test
    void check() throws Exception
    {
        final String[] expected = {
            "31:27: Do not hardcode the system temporary directory in a test." + ADVICE,
            "32:26: Do not hardcode the system temporary directory in a test." + ADVICE,
            "34:37: Do not call File.createTempFile() without an explicit parent directory in a test." + ADVICE,
            "36:38: Do not call Files.createTempFile() without a parent directory in a test." + ADVICE,
            "37:43: Do not call Files.createTempDirectory() without a parent directory in a test." + ADVICE
        };

        verify(this.checkConfig, getPath("TestClassWithTemporaryFiles.java"), expected);
    }

    @Override
    public String getPackageLocation()
    {
        return "org/xwiki/tool/checkstyle/test/temporaryfile";
    }
}
